services:
  app:
    build: .
    restart: on-failure
    volumes: 
      - ./app:/app
    ports: 
      - "3000:3000"
    environment: 
      PYTHONUNBUFFERED: 1
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
    shm_size: 2g